import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/Components/NavBar/NavBar";
import Link from "next/link";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "The Reddit App",
  description: "Generated by create next app",
  referrer: "no-referrer",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full h-screen font-roboto">
        <main className="w-full justify-center flex flex-col">
          <NavBarComponent />
          <div className=" w-full justify-center flex flex-row ">
            <div className="flex flex-col items-end flex-1/4 h-fit top-24 sticky">
              <div className=" flex flex-col items-start font-light text-2xl px-2 w-1/2 ">
                <Link href="/" className="font-light">
                  <span className="font-light">Home</span>
                </Link>
                <Link href="/subreddits">Subreddits</Link>
                <Link href="/user/saved">Saved</Link>
                <Link href="/r/friends">Friends</Link>
              </div>
            </div>
            <div className=" flex-2/3 items-start justify-center flex flex-col">
              <div className="flex flex-col max-w-[40vw] w-[40vw] justify-center border  border-twitter-gray">
                {children}
              </div>
            </div>
          </div>
          <div className="w-full h-10 my-2 justify-center">Mi Mi Mi Mi </div>
          <Toaster
            position="bottom-center"
            duration={1000}
            expand={false}
            theme="dark"
            toastOptions={{
              classNames: {
                title: "!text-white ",
                toast: "!bg-pink-900",
              },
              style: { width: "fit-content", marginInline: "auto" },
            }}
            className="flex justify-center"
            style={{
              animation: "none",
              animationDuration: "0",
              animationTimeline: "none",
              alignmentBaseline: "unset",
              animationComposition: "unset",
              animationDelay: "unset",
              animationDirection: "unset",
              animationFillMode: "unset",
              animationPlayState: "unset",
              animationName: "none",
              animationIterationCount: "0",
              animationRange: 0,
              MozAnimation: "none",
            }}
          />
        </main>
      </body>
    </html>
  );
}
