import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/Components/NavBar/NavBar";
import Link from "next/link";
export const metadata: Metadata = {
  title: "The Reddit App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full h-screen font-roboto">
        <main className="w-full justify-center flex flex-col">
          <NavBarComponent />
          <div className=" w-full justify-center flex flex-row ">
            <div className="flex flex-col items-end flex-1/4 h-fit top-24 sticky">
              <div className=" flex flex-col items-start font-light text-2xl px-2 w-1/2 ">
                <Link href="/" className="font-light">
                  <span className="font-light">Home</span>
                </Link>
                <Link href="/">Subreddits</Link>
                <Link href="/user/saved">Saved</Link>
                <Link href="/r/friends">Friends</Link>
              </div>
            </div>
            <div className=" flex-2/3 items-start justify-center flex flex-col">
              <div className="flex flex-col justify-center border border-twitter-gray">
                {children}
              </div>
            </div>
          </div>
          <div className="w-full h-10 my-2 justify-center">Mi Mi Mi Mi </div>
        </main>
      </body>
    </html>
  );
}
