import type { Metadata } from "next";
import "./globals.css";
import NavBarComponent from "@/Components/NavBar/NavBar";
import Link from "next/link";
import { Toaster } from "sonner";
export const metadata: Metadata = {
  title: "The Reddit App",
  description: "Generated by create next app",
  referrer: "no-referrer",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col w-full h-screen font-roboto">
        <main className="w-full justify-center flex flex-col">
          <NavBarComponent />
          <div className=" w-full justify-center flex flex-row   ">
            <div className="flex flex-col left-[12.5%] max-w-[275px] h-fit top-24 absolute  max-md:hidden max-lg:flex-auto">
              <div className=" flex flex-col fixed items-start font-light text-2xl px-2 w-fit ">
                <Link href="/" className="font-light">
                  <span className="font-light">Home</span>
                </Link>
                <Link href="/subreddits">Subreddits</Link>
                <Link href="/user/saved">Saved</Link>
                <Link href="/r/friends">Friends</Link>
              </div>
            </div>
            <div className="  items-center justify-center flex flex-col max-lg:flex-auto max-lg:items-center ">
              <div className="flex flex-col max-w-[766px] w-full justify-center border  border-twitter-gray">
                {children}
              </div>
            </div>
          </div>
          <div className="w-full h-10 my-2 justify-center">Mi Mi Mi Mi </div>
          <Toaster
            position="bottom-center"
            duration={1000}
            expand={false}
            theme="dark"
            toastOptions={{
              classNames: {
                title: "!text-white ",
                toast: "!bg-pink-900",
              },
              style: { width: "fit-content", marginInline: "auto" },
            }}
            className="flex justify-center"
          />
        </main>
      </body>
    </html>
  );
}
